#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
A simple script that makes swithcing shadowsocks servers much easier.
Put this script under the same directory config.json locates.
There should be an array named 'server_password' which contains a list of
(host, password, method) tuoples in the  config.json.
"""
import json
import os.path
import shutil


def main():
    config_fil_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.json")
    with open(config_fil_path) as config_fil:
        configs = json.loads(config_fil.read())

    server_infos = configs['server_password']
    keyword = raw_input("Please type the filter keyword:")

    matches = filter(lambda x: keyword in x[0], server_infos)
    if len(matches) != 1:
        print 'Can not find exactly 1 match.\nMatches: {}'.format(json.dumps(matches))
        return
    else:
        server, password, method = matches[0]
        host, port = server.split(':')
        configs['server'] = host
        configs['server_port'] = port
        configs['password'] = password
        configs['method'] = method

        shutil.copy2(config_fil_path, config_fil_path + '.bak')
        with open(config_fil_path, 'w') as config_fil:
            config_fil.write(json.dumps(configs, indent=4))

if __name__ == '__main__':
    main()
